"use strict";
// Load .env before anything else so API handlers have access to environment variables
try{require("fs").readFileSync(require("path").join(__dirname,"../.env"),"utf8").split("\n").forEach(l=>{const t=l.trim();if(!t||t.startsWith("#"))return;const eq=t.indexOf("=");if(eq<1)return;const k=t.slice(0,eq).trim(),v=t.slice(eq+1).trim();if(k&&!process.env[k])process.env[k]=v;});}catch(_){}
const http=require("http"),fs=require("fs"),path=require("path"),url=require("url");
const PORT=3000,ROOT=path.join(__dirname,"..");
const MIME={".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".ico":"image/x-icon",".txt":"text/plain",".xml":"application/xml",".webmanifest":"application/manifest+json"};
const RW=[{s:"/",d:"/pages/index.html"},{s:"/privacy-policy",d:"/pages/privacy-policy.html"},{s:"/terms",d:"/pages/terms-and-conditions.html"},{s:"/booking",d:"/pages/booking.html"},{s:"/booking-confirmation",d:"/pages/booking-confirmation.html"},{s:"/admin",d:"/pages/admin/login.html"},{s:"/admin/login",d:"/pages/admin/login.html"},{s:"/admin/dashboard",d:"/pages/admin/dashboard.html"},{s:"/admin/reservations",d:"/pages/admin/reservations.html"},{s:"/admin/rooms",d:"/pages/admin/rooms.html"},{s:"/admin/guests",d:"/pages/admin/guests.html"},{s:"/admin/calendar",d:"/pages/admin/calendar.html"},{s:"/admin/settings",d:"/pages/admin/settings.html"}];
function setSec(r){r.setHeader("X-Content-Type-Options","nosniff");r.setHeader("X-Frame-Options","SAMEORIGIN");r.setHeader("Referrer-Policy","strict-origin-when-cross-origin");}
function parseBody(req){return new Promise(res=>{let d="";req.on("data",c=>{d+=c;});req.on("end",()=>{try{res(d?JSON.parse(d):{});}catch{res({});}});});}
function makeRes(nr){return{statusCode:200,status(c){this.statusCode=c;return this;},setHeader(k,v){nr.setHeader(k,v);return this;},getHeader(k){return nr.getHeader(k);},json(o){if(!nr.headersSent){nr.setHeader("Content-Type","application/json");setSec(nr);nr.writeHead(this.statusCode);}nr.end(JSON.stringify(o));},end(d){if(!nr.headersSent){setSec(nr);nr.writeHead(this.statusCode);}nr.end(d||"");}};}
function resolveApi(p){const rel=p.slice(4);for(const c of[path.join(ROOT,"api",rel+".js"),path.join(ROOT,"api",rel,"index.js")]){if(fs.existsSync(c))return{file:c,params:{}};}const parts=rel.split("/").filter(Boolean);for(let i=parts.length-1;i>=0;i--){const t=path.join(ROOT,"api",...parts.slice(0,i),"[id].js");if(fs.existsSync(t))return{file:t,params:{id:parts[i]}};}return null;}
http.createServer(async(nr,nodeRes)=>{
  const parsed=url.parse(nr.url,true),pn=decodeURIComponent(parsed.pathname);
  if(pn.startsWith("/api/")){const m=resolveApi(pn);if(!m){nodeRes.writeHead(404,{"Content-Type":"application/json"});nodeRes.end(JSON.stringify({error:"Not found"}));return;}const body=["POST","PUT","PATCH"].includes(nr.method)?await parseBody(nr):{};const req={method:nr.method,headers:nr.headers,query:{...parsed.query,...m.params},body,socket:nr.socket};const res=makeRes(nodeRes);delete require.cache[require.resolve(m.file)];try{const h=require(m.file);await h(req,res);}catch(e){console.error("[API]",pn,e.message);if(!nodeRes.headersSent){nodeRes.writeHead(500,{"Content-Type":"application/json"});nodeRes.end(JSON.stringify({error:"Internal error"}));}}return;}
  let fp=null;for(const r of RW){if(pn===r.s){fp=path.join(ROOT,r.d);break;}}if(!fp)fp=path.join(ROOT,pn);
  if(!fp.startsWith(ROOT)){nodeRes.writeHead(403);nodeRes.end("Forbidden");return;}
  if(!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){nodeRes.writeHead(404,{"Content-Type":"text/html"});nodeRes.end("<h1>404</h1>");return;}
  const ext=path.extname(fp).toLowerCase();
  try{const c=fs.readFileSync(fp);setSec(nodeRes);nodeRes.writeHead(200,{"Content-Type":MIME[ext]||"application/octet-stream"});nodeRes.end(c);}catch{nodeRes.writeHead(500);nodeRes.end("Error");}
}).listen(PORT,()=>{console.log("SILVERLINE DEV SERVER READY");console.log("http://localhost:"+PORT+"/");console.log("Booking: http://localhost:"+PORT+"/booking");console.log("Admin:   http://localhost:"+PORT+"/admin");});
